name: persistent_header_adaptive
description: This ia a package that provide capability to create SliverPersistentHeader with intrinsic height
version: 1.1.0
homepage: https://github.com/camillobucciarelli/persistent_header_adaptive
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"
  flutter: ">=2.13.0-0.1-pre"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
